[package]
name = "lemmy_server"
version = "0.0.2"
edition = "2018"

[profile.release]
lto = true

[workspace]
members = [
    "lemmy_api",
    "lemmy_apub",
    "lemmy_utils",
    "lemmy_db",
    "lemmy_structs",
    "lemmy_rate_limit",
    "lemmy_websocket",
]

[dependencies]
lemmy_api = { path = "./lemmy_api" }
lemmy_apub = { path = "./lemmy_apub" }
lemmy_utils = { path = "./lemmy_utils" }
lemmy_db = { path = "./lemmy_db" }
lemmy_structs = { path = "./lemmy_structs" }
lemmy_rate_limit = { path = "./lemmy_rate_limit" }
lemmy_websocket = { path = "./lemmy_websocket" }
diesel = "1.4.5"
diesel_migrations = "1.4.0"
chrono = { version = "0.4.19", features = ["serde"] }
serde = { version = "1.0.118", features = ["derive"] }
actix = "0.10.0"
actix-web = { version = "3.3.2", default-features = false, features = ["rustls"] }
actix-files = { version = "0.4.1", default-features = false }
actix-web-actors = { version = "3.0.0", default-features = false }
awc = { version = "2.0.3", default-features = false }
log = "0.4.11"
env_logger = "0.8.2"
strum = "0.20.0"
lazy_static = "1.4.0"
rss = "1.9.0"
url = { version = "2.2.0", features = ["serde"] }
openssl = "0.10.30"
http-signature-normalization-actix = { version = "0.4.1", default-features = false, features = ["sha-2"] }
tokio = "0.3.5"
sha2 = "0.9.2"
anyhow = "1.0.35"
reqwest = { version = "0.10.9", features = ["json"] }
activitystreams = "0.7.0-alpha.8"
actix-rt = { version = "1.1.1", default-features = false }
serde_json = { version = "1.0.60", features = ["preserve_order"] }

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
